### PR TITLE
Initial docker-compose for magento 1

### PR DESCRIPTION
**Pull request by sinukaarel**
Adds initial Docker compose for Magento 1 module development.

Adds initial tusk files for easy shortcuts to install sample data and magneto.

### CODE REVIEW

**Comment by kaittodesk** [comment]
With other plugins/extensions/modules we have tried to use `mysql:5.7` image for the sandbox environment database. Was there a specific reason you chose `bitnami/mariadb:10.3`? Is it possible to change the database image to `mysql:5.7`?

**Comment by sinukaarel** [comment]
> With other plugins/extensions/modules we have tried to use `mysql:5.7` image for the sandbox environment database. Was there a specific reason you chose `bitnami/mariadb:10.3`? Is it possible to change the database image to `mysql:5.7`?

The initial idea was to use the same DB images for Magento 1 and Magneto 2 development. I took the `bitnami/mariadb:10.3` image as I was using bitnami image for Magento2. I actually no longer use bitnami image for Magento 2 as it was not suitable for our use-case. (They will have to change symlinks handling).I can change it to mysql:5.7. 

MariaDB image is smaller docker `mariadb` image is 278M and `mysql` one 435M. I also liked the documentation there more.

Why did you prefer to use a 5.7 version, not a newer  8.X one?

**Comment by sinukaarel** [comment]
I changed the default port to 8080 so it matches other development containers and changed to mysql for DB. https://github.com/sendsmaily/Sendsmaily-Sync-for-Magento/pull/11/commits/2368c974d53c1b6246f2909fc0556ef9c6764a66

**Comment by kaittodesk** [comment]
> Why did you prefer to use a 5.7 version, not a newer 8.X one?

It aligns with our legacy stack and not all versions of plugins may work with newer versions of MySQL. Although MariaDB 10.3 is also built on MySQL 5.7 it can still have some compatibility issues with different platforms/frameworks/CMSs.

**Pull request merged**
